import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import { join } from "node:path"

const REPO_ROOT = join(import.meta.dir, "../..")

describe("CI policy", () => {
  test("package scripts expose ci policy gate", async () => {
    const pkg = JSON.parse(await readFile(join(REPO_ROOT, "package.json"), "utf-8")) as {
      scripts: Record<string, string>
    }

    expect(pkg.scripts["ci:policy"]).toContain("ci-policy-check.mjs")
    expect(pkg.scripts["product:policy"]).toContain("product-policy-check.mjs")
    expect(pkg.scripts["dependency:policy"]).toContain("dependency-contract-check.mjs")
    expect(pkg.scripts["deploy:policy"]).toContain("deploy-contract-check.mjs")
    expect(pkg.scripts["api:policy"]).toContain("api-stability-check.mjs")
    expect(pkg.scripts["adoption:policy"]).toContain("adoption-proof-check.mjs")
    expect(pkg.scripts["ai:policy"]).toContain("ai-policy-check.mjs")
    expect(pkg.scripts["dx:policy"]).toContain("dx-policy-check.mjs")
    expect(pkg.scripts["maturity:policy"]).toContain("maturity-policy-check.mjs")
    expect(pkg.scripts["runtime:policy"]).toContain("runtime-diagnostics-policy-check.mjs")
    expect(pkg.scripts["runtime:security:policy"]).toContain("runtime-security-contract-check.mjs")
    expect(pkg.scripts["critical:surface"]).toContain("critical-surface-check.mjs")
    expect(pkg.scripts["test:critical-surface"]).toContain("router-navigation.test.ts")
    expect(pkg.scripts["benchmarks:policy"]).toContain("benchmark-policy-check.mjs")
    expect(pkg.scripts["benchmarks:realworld:check"]).toContain("realworld-benchmark-check.mjs")
    expect(pkg.scripts["examples:policy"]).toContain("examples-policy-check.mjs")
    expect(pkg.scripts["test:confidence"]).toContain("production-large-app-runtime.test.ts")
    expect(pkg.scripts["test:confidence"]).toContain("canonical-recipes-runtime.test.ts")
    expect(pkg.scripts["verify:security"]).toContain("bun run product:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run dependency:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run deploy:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run api:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run adoption:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run ai:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run dx:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run maturity:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run runtime:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run runtime:security:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run benchmarks:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run benchmarks:realworld:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run examples:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run critical:surface")
    expect(pkg.scripts["verify:security"]).toContain("bun run ci:policy")
    expect(pkg.scripts["verify:security"]).toContain("bun run compiler:promotion:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run build:promotion:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run backend:switch:evidence:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run backend:default-switch:review:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run compiler:default:rehearsal:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run build:default:rehearsal:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run backend:candidate:rollout:check")
    expect(pkg.scripts["verify:security"]).toContain("bun run test:critical-surface")
    expect(pkg.scripts["backend:candidate:evidence:verify"]).toContain("compiler:evidence:verify")
    expect(pkg.scripts["backend:candidate:evidence:verify"]).toContain("build:evidence:verify")
    expect(pkg.scripts["backend:candidate:verify"]).toContain("backend:candidate:evidence:verify")
    expect(pkg.scripts["verify:security"]).toContain("bun run test:confidence")
  })

  test("CI workflow enforces security and release-train gates", async () => {
    const ci = await readFile(join(REPO_ROOT, ".github/workflows/ci.yml"), "utf-8")
    expect(ci).toContain("bun install --frozen-lockfile")
    expect(ci).toContain("bun run product:policy")
    expect(ci).toContain("bun run dependency:policy")
    expect(ci).toContain("bun run deploy:policy")
    expect(ci).toContain("bun run api:policy")
    expect(ci).toContain("bun run adoption:policy")
    expect(ci).toContain("bun run ai:policy")
    expect(ci).toContain("bun run dx:policy")
    expect(ci).toContain("bun run maturity:policy")
    expect(ci).toContain("bun run runtime:policy")
    expect(ci).toContain("bun run runtime:security:policy")
    expect(ci).toContain("bun run benchmarks:policy")
    expect(ci).toContain("bun run benchmarks:realworld:check")
    expect(ci).toContain("bun run examples:policy")
    expect(ci).toContain("bun run critical:surface")
    expect(ci).toContain("bun run ci:policy")
    expect(ci).toContain("bun run compiler:promotion:check")
    expect(ci).toContain("bun run build:promotion:check")
    expect(ci).toContain("bun run backend:switch:evidence:check")
    expect(ci).toContain("bun run backend:default-switch:review:check")
    expect(ci).toContain("bun run compiler:default:rehearsal:check")
    expect(ci).toContain("bun run build:default:rehearsal:check")
    expect(ci).toContain("bun run backend:candidate:verify")
    expect(ci).toContain("bun run verify:security")
    expect(ci).toContain("bun run test:critical-surface")
    expect(ci).toContain("bun run test:confidence")
    expect(ci).toContain("bun test")
    expect(ci).toContain("bun run test:provider-smoke")
    expect(ci).toContain("bun run test:browser-smoke")
    expect(ci).toContain("ubuntu-latest")
    expect(ci).toContain("macos-latest")
    expect(ci).toContain("windows-latest")
    expect(ci).toContain("npx playwright install --with-deps ${{ matrix.browser }}")
    expect(ci).toContain("chromium")
    expect(ci).toContain("firefox")
    expect(ci).toContain("webkit")
    expect(ci).toContain("bun run release:train:check")
    expect(ci).toContain("bun run release:checklist:check")
    expect(ci).toContain("npm run release:check")
    expect(ci).toContain("npm run install:matrix")
    expect(ci).toContain("npm run release:smoke")
    expect(ci).toContain("actions/setup-node@v4")
  })

  test("release-train workflow supports stable/canary/rc validation", async () => {
    const workflow = await readFile(join(REPO_ROOT, ".github/workflows/release-train.yml"), "utf-8")
    expect(workflow).toContain("workflow_dispatch")
    expect(workflow).toContain("stable")
    expect(workflow).toContain("canary")
    expect(workflow).toContain("rc")
  })

  test("CI policy doc defines required gates and Bun contract", async () => {
    const doc = await readFile(join(REPO_ROOT, "docs/CI_POLICY.md"), "utf-8")
    expect(doc).toContain("Required Gates")
    expect(doc).toContain("Change-Sensitive Rules")
    expect(doc).toContain("Confidence Suite")
    expect(doc).toContain("Examples Surface")
    expect(doc).toContain("Dependency Surface")
    expect(doc).toContain("Deploy Surface")
    expect(doc).toContain("API Stability Surface")
    expect(doc).toContain("Adoption Proof Surface")
    expect(doc).toContain("AI Workflow Surface")
    expect(doc).toContain("DX Surface")
    expect(doc).toContain("Maturity Surface")
    expect(doc).toContain("Runtime Diagnostics Surface")
    expect(doc).toContain("Runtime Security Surface")
    expect(doc).toContain("Benchmark Evidence Surface")
    expect(doc).toContain("Critical Surface Suite")
    expect(doc).toContain("Runtime Smoke")
    expect(doc).toContain("Support Matrix")
    expect(doc).toContain("Release Train")
    expect(doc).toContain("compiler:promotion:check")
    expect(doc).toContain("build:promotion:check")
    expect(doc).toContain("backend:switch:evidence:check")
    expect(doc).toContain("backend:default-switch:review:check")
    expect(doc).toContain("compiler:default:rehearsal:check")
    expect(doc).toContain("build:default:rehearsal:check")
    expect(doc).toContain("backend:candidate:rollout:check")
    expect(doc).toContain("backend:candidate:verify")
    expect(doc).toContain("bun run critical:surface")
    expect(doc).toContain("bun run test:critical-surface")
    expect(doc).toContain("docs/DEPLOY_CONTRACT.json")
    expect(doc).toContain("docs/PUBLIC_SURFACE_MANIFEST.json")
    expect(doc).toContain("docs/RELEASE_CONTRACT.json")
    expect(doc).toContain("docs/BENCHMARK_CONTRACT.json")
    expect(doc).toContain("docs/RUNTIME_SECURITY_CONTRACT.json")
    expect(doc).toContain("docs/DIAGNOSTICS_CONTRACT.json")
    expect(doc).toContain("Bun Contract")
    expect(doc).toContain("Product Standard")
    expect(doc).toContain("bun@1.3.9")
    expect(doc).toContain("npm run release:check")
    expect(doc).toContain("npm run install:matrix")
    expect(doc).toContain("npm run release:smoke")
    expect(doc).toContain("bun run test:provider-smoke")
    expect(doc).toContain("bun run test:browser-smoke")
    expect(doc).toContain("ubuntu-latest")
    expect(doc).toContain("macos-latest")
    expect(doc).toContain("windows-latest")
    expect(doc).toContain("chromium")
    expect(doc).toContain("firefox")
    expect(doc).toContain("webkit")
  })
})
