import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import { join } from "node:path"

const ROOT = process.cwd()

describe("top-tier roadmap and reactive docs", () => {
  test("top-tier roadmap defines the single six-stage execution plan", async () => {
    const roadmap = await readFile(join(ROOT, "docs", "TOP_TIER_ROADMAP.md"), "utf-8")
    expect(roadmap).toContain("single canonical execution plan")
    expect(roadmap).toContain("Stage 1: Navigation / Hydration Hardening")
    expect(roadmap).toContain("Stage 2: Reactive Diagnostics / Devtools")
    expect(roadmap).toContain("Stage 3: Wider CI / Support Matrix")
    expect(roadmap).toContain("Stage 4: Compiler Platform Closure")
    expect(roadmap).toContain("Stage 5: Fixture-App / Adapter / Plugin Conformance")
    expect(roadmap).toContain("Stage 6: Performance Evidence on Realistic Apps")
    expect(roadmap).toContain("Implementation Order")
    expect(roadmap).toContain("correctness first")
    expect(roadmap).toContain("Non-Goals")
  })

  test("reactive docs define runtime story and benchmark surface", async () => {
    const runtimeDoc = await readFile(join(ROOT, "docs", "REACTIVE_RUNTIME.md"), "utf-8")
    const benchmarkDoc = await readFile(join(ROOT, "docs", "REACTIVE_BENCHMARKS.md"), "utf-8")
    const hydrationDoc = await readFile(join(ROOT, "docs", "REACTIVE_HYDRATION.md"), "utf-8")
    const debuggingDoc = await readFile(join(ROOT, "docs", "REACTIVE_DEBUGGING.md"), "utf-8")
    const gapsDoc = await readFile(join(ROOT, "docs", "REACTIVE_MEASUREMENT_GAPS.md"), "utf-8")
    expect(runtimeDoc).toContain("fine-grained reactive model")
    expect(runtimeDoc).toContain("Use `gorsee/client` for the public reactive surface")
    expect(runtimeDoc).toContain("getReactiveTraceArtifact")
    expect(runtimeDoc).toContain("Non-Goals")
    expect(benchmarkDoc).toContain("`benchmarks/ssr-throughput`")
    expect(benchmarkDoc).toContain("`benchmarks/js-framework-bench`")
    expect(benchmarkDoc).toContain("Interpretation Rules")
    expect(hydrationDoc).toContain("Prefer the smallest hydration boundary")
    expect(debuggingDoc).toContain("getReactiveTraceArtifact()")
    expect(debuggingDoc).toContain("dependency edges")
    expect(debuggingDoc).toContain("Current Gaps")
    expect(gapsDoc).toContain("Hydration")
    expect(gapsDoc).toContain("Resources")
    expect(gapsDoc).toContain("Mutations")
  })

  test("README links the canonical roadmap and reactive docs", async () => {
    const readme = await readFile(join(ROOT, "README.md"), "utf-8")
    expect(readme).toContain("Top-Tier Roadmap")
    expect(readme).toContain("Reactive Runtime")
    expect(readme).toContain("Reactive Benchmarks")
    expect(readme).toContain("Reactive Hydration")
    expect(readme).toContain("Reactive Debugging")
    expect(readme).toContain("Reactive Measurement Gaps")
    expect(readme).toContain("Build Diagnostics")
    expect(readme).toContain("Benchmark Methodology")
    expect(readme).toContain("SSR Benchmark Proof")
    expect(readme).toContain("DOM Benchmark Proof")
    expect(readme).toContain("Benchmark Artifacts")
    expect(readme).toContain("Benchmark Release Discipline")
    expect(readme).toContain("Runtime Failures")
    expect(readme).toContain("Cache Invalidation")
    expect(readme).toContain("Streaming and Hydration Failures")
    expect(readme).toContain("Runtime Triage")
    expect(readme).toContain("Starter Failures")
    expect(readme).toContain("AI Workflows")
    expect(readme).toContain("AI IDE Sync Workflow")
    expect(readme).toContain("AI MCP Workflow")
    expect(readme).toContain("AI Bridge Workflow")
    expect(readme).toContain("AI Tool Builders")
    expect(readme).toContain("AI Surface Stability")
    expect(readme).toContain("AI Session Packs")
    expect(readme).toContain("AI Debugging Workflows")
    expect(readme).toContain("Starter Onboarding")
    expect(readme).toContain("Migration Guide")
    expect(readme).toContain("Upgrade Playbook")
    expect(readme).toContain("Deploy Target Guide")
    expect(readme).toContain("First Production Rollout")
    expect(readme).toContain("Auth / Cache / Data Paths")
    expect(readme).toContain("Recipe Boundaries")
    expect(readme).toContain("Workspace Adoption")
    expect(readme).toContain("Downstream Testing")
    expect(readme).toContain("Team Failures")
    expect(readme).toContain("Maturity Policy")
    expect(readme).toContain("Dependency Policy")
    expect(readme).toContain("Compatibility Guardrails")
    expect(readme).toContain("Ambiguity Policy")
    expect(readme).toContain("DX Feedback Loop")
    expect(readme).toContain("Evidence Policy")
    expect(readme).toContain("Roadmap Completion Policy")
  })
})
