import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import { join } from "node:path"

const REPO_ROOT = join(import.meta.dir, "../..")

describe("release surface contracts", () => {
  test("release-check rejects unpublished repository/homepage metadata drift", async () => {
    const script = await readFile(join(REPO_ROOT, "scripts/release-check.mjs"), "utf-8")

    expect(script).toContain('packed package repository must be')
    expect(script).toContain('packed package homepage must be')
    expect(script).toContain('packed package bugs.url must be')
    expect(script).toContain('packedPackage.bin?.gorsee')
    expect(script).toContain('packedPackage.types !== "./dist-pkg/index.d.ts"')
    expect(script).toContain('"./compat": "./dist-pkg/compat.js"')
    expect(script).toContain('"./auth": "./dist-pkg/auth/index.js"')
    expect(script).toContain('"./forms": "./dist-pkg/forms/index.js"')
    expect(script).toContain('"./routes": "./dist-pkg/routes/index.js"')
    expect(script).toContain('"./i18n": "./dist-pkg/i18n/index.js"')
    expect(script).toContain('"./content": "./dist-pkg/content/index.js"')
    expect(script).toContain('"./deploy": "./dist-pkg/deploy/index.js"')
    expect(script).toContain('"./testing": "./dist-pkg/testing/index.js"')
    expect(script).toContain('packed tarball must include dist-pkg/index.js')
    expect(script).toContain('packed tarball must include dist-pkg/index.d.ts')
    expect(script).toContain('packed tarball must include bin/gorsee.js')
    expect(script).toContain('packed tarball must not ship raw src/index.ts')
    expect(script).toContain('packed export must remain a direct JS entry for ${key}')
    expect(script).toContain('packed tarball missing JS entry for ${key}: ${exportPath}')
    expect(script).toContain('packed tarball missing declaration entry for ${key}: ${declarationPath}')
    expect(script).toContain('packed export drift for ${key}')
  })

  test("release-smoke preserves starter product and AI guidance", async () => {
    const script = await readFile(join(REPO_ROOT, "scripts/release-smoke.mjs"), "utf-8")
    const readme = await readFile(join(REPO_ROOT, "README.md"), "utf-8")
    const frameworkDoctrine = await readFile(join(REPO_ROOT, "docs/FRAMEWORK_DOCTRINE.md"), "utf-8")
    const applicationModes = await readFile(join(REPO_ROOT, "docs/APPLICATION_MODES.md"), "utf-8")

    expect(script).toContain("function exerciseInstalledSubpathImports(rootDir)")
    expect(script).toContain('await import("gorsee/auth")')
    expect(script).toContain('await import("gorsee/forms")')
    expect(script).toContain('await import("gorsee/routes")')
    expect(script).toContain('await import("gorsee/i18n")')
    expect(script).toContain('await import("gorsee/content")')
    expect(script).toContain('await import("gorsee/deploy")')
    expect(script).toContain('await import("gorsee/testing")')
    expect(script).toContain('exerciseInstalledSubpathImports(smokeRoot)')
    expect(script).toContain('gorsee/auth packed export missing createAuth')
    expect(script).toContain('gorsee/forms packed export missing defineFormAction')
    expect(script).toContain('gorsee/routes packed export missing createTypedRoute')
    expect(script).toContain('gorsee/i18n packed export missing setupI18n')
    expect(script).toContain('gorsee/content packed export missing parseFrontmatter')
    expect(script).toContain('gorsee/deploy packed export missing generateDockerfile')
    expect(script).toContain('gorsee/testing packed export missing createTestRequest')
    expect(script).toContain('runIn(appDir, appBin, ["check"])')
    expect(script).toContain('runIn(smokeRoot, "node", [join(standaloneCreateRoot, "index.js"), "standalone-smoke-app"])')
    expect(script).toContain('const gorseeBin = resolveInstalledGorseeBin(smokeRoot)')
    expect(script).toContain('return join(rootDir, "node_modules", "gorsee", "dist-pkg", "bin", "gorsee.js")')
    expect(script).toContain('runIn(standaloneAppDir, standaloneAppBin, ["check"], { env: bunTempEnv })')
    expect(script).toContain('runIn(appDir, appBin, ["deploy", "fly", "--runtime", "node"])')
    expect(script).toContain('runIn(appDir, appBin, ["deploy", "docker", "--runtime", "node"])')
    expect(script).toContain('import("./dist/prod-node.js")')
    expect(script).toContain('import("./dist/server-handler-node.js")')
    expect(script).toContain('cpSync(exampleDir, sandboxRoot, { recursive: true })')
    expect(script).toContain('const bin = join(sandboxRoot, "node_modules", ".bin", "gorsee")')
    expect(script).toContain('const bin = join(sandboxRoot, "apps", "web", "node_modules", ".bin", "gorsee")')
    expect(script).toContain('import type { Context } from "gorsee/server"')
    expect(script).toContain('import { createAuth, createMemorySessionStore } from "gorsee/auth"')
    expect(script).toContain("release smoke app lost gorsee/auth scaffold import contract")
    expect(script).toContain("release smoke app lost gorsee/server context import contract")
    expect(script).toContain("release smoke app lost createAuth auth surface contract")
    expect(script).toContain("release smoke app lost createMemorySessionStore auth surface contract")
    expect(script).toContain("canonical examples surface lost secure-saas reference")
    expect(script).toContain("canonical examples surface lost content-site reference")
    expect(script).toContain("canonical examples surface lost plugin-stack reference")
    expect(script).toContain("canonical examples surface lost frontend-app reference")
    expect(script).toContain("canonical examples surface lost server-api reference")
    expect(script).toContain('exerciseExample(join(repoRoot, "examples", "frontend-app"), "app.config.ts", \'mode: "frontend"\')')
    expect(script).toContain('exerciseExample(join(repoRoot, "examples", "secure-saas"), join("routes", "app", "_middleware.ts"), "auth.protect")')
    expect(script).toContain('exerciseExample(join(repoRoot, "examples", "content-site"), join("routes", "_middleware.ts"), \'mode: "public"\')')
    expect(script).toContain("docs/CANONICAL_RECIPES.md")
    expect(script).toContain("docs/RUNTIME_FAILURES.md")
    expect(script).toContain("docs/STARTER_FAILURES.md")
    expect(script).toContain("docs/AI_WORKFLOWS.md")
    expect(script).toContain("docs/AI_SESSION_PACKS.md")
    expect(script).toContain("docs/UPGRADE_PLAYBOOK.md")
    expect(script).toContain("docs/WORKSPACE_ADOPTION.md")
    expect(script).toContain("starter README lost product positioning contract")
    expect(script).toContain("starter README lost mature product guidance")
    expect(script).toContain("starter README lost canonical server runtime guidance")
    expect(script).toContain("starter README lost scoped import guidance")
    expect(script).toContain("starter README lost runtime failures guidance")
    expect(script).toContain("starter README lost AI workflows guidance")
    expect(script).toContain("starter README lost upgrade playbook guidance")
    expect(script).toContain("standalone create app lost canonical server runtime guidance")
    expect(script).toContain("standalone create app lost lockfile reproducibility guidance")
    expect(script).toContain("FRAMEWORK.md lost mature product doctrine")
    expect(script).toContain("FRAMEWORK.md lost AI artifact contract guidance")
    expect(script).toContain("FRAMEWORK.md lost runtime triage guidance")
    expect(script).toContain("FRAMEWORK.md lost AI workflows guidance")
    expect(script).toContain("FRAMEWORK.md lost starter onboarding guidance")
    expect(script).toContain('exerciseExample(join(repoRoot, "examples", "agent-aware-ops"), "app.config.ts", "enabled: true")')
    expect(script).toContain('exerciseExample(join(repoRoot, "examples", "plugin-stack"), join("routes", "api", "plugins.ts"), \'service: "gorsee-plugin-stack"\')')
    expect(script).toContain('exerciseExample(join(repoRoot, "examples", "server-api"), join("routes", "api", "index.ts"), \'service: "gorsee-server-api"\')')
    expect(script).toContain('examples", "workspace-monorepo')
    expect(script).toContain("workspace example lost shared import contract")
    expect(script).toContain("workspace example lost gorsee/auth contract")
    expect(script).toContain("workspace example lost gorsee/server context contract")
    expect(readme).toContain("Application Modes")
    expect(frameworkDoctrine).toContain("frontend")
    expect(frameworkDoctrine).toContain("fullstack")
    expect(frameworkDoctrine).toContain("server")
    expect(applicationModes).toContain("This document defines the canonical application modes for Gorsee.")
    expect(applicationModes).toContain("`frontend`")
    expect(applicationModes).toContain("`fullstack`")
    expect(applicationModes).toContain("`server`")
  })
})
