import { describe, expect, test } from "bun:test"
import { readFile } from "node:fs/promises"
import { join } from "node:path"

const REPO_ROOT = join(import.meta.dir, "../..")

describe("release train docs and scripts", () => {
  test("release policy doc defines stable/canary/rc workflow", async () => {
    const doc = await readFile(join(REPO_ROOT, "docs/RELEASE_POLICY.md"), "utf-8")
    expect(doc).toContain("Stable")
    expect(doc).toContain("Canary")
    expect(doc).toContain("Release Candidate")
    expect(doc).toContain("canary first")
    expect(doc).toContain("compiler:promotion:check")
    expect(doc).toContain("build:promotion:check")
    expect(doc).toContain("backend-switch-evidence-check.mjs")
    expect(doc).toContain("backend-default-switch-review-check.mjs")
    expect(doc).toContain("compiler-default-switch-rehearsal-check.mjs")
    expect(doc).toContain("build-default-switch-rehearsal-check.mjs")
    expect(doc).toContain("docs/COMPILER_DEFAULT_SWITCH_DOSSIER.md")
    expect(doc).toContain("docs/BUILD_DEFAULT_SWITCH_DOSSIER.md")
    expect(doc).toContain("docs/EXAMPLES_POLICY.md")
    expect(doc).toContain("docs/RUNTIME_FAILURES.md")
    expect(doc).toContain("docs/AI_WORKFLOWS.md")
    expect(doc).toContain("docs/UPGRADE_PLAYBOOK.md")
    expect(doc).toContain("docs/EVIDENCE_POLICY.md")
  })

  test("release checklist doc defines operator-facing channel checklists", async () => {
    const doc = await readFile(join(REPO_ROOT, "docs/RELEASE_CHECKLIST.md"), "utf-8")
    expect(doc).toContain("## Stable")
    expect(doc).toContain("## Canary")
    expect(doc).toContain("## Release Candidate")
    expect(doc).toContain("bun run verify:security")
    expect(doc).toContain("bun run compiler:promotion:check")
    expect(doc).toContain("bun run build:promotion:check")
    expect(doc).toContain("bun run backend:switch:evidence:check")
    expect(doc).toContain("bun run backend:default-switch:review:check")
    expect(doc).toContain("bun run compiler:default:rehearsal:check")
    expect(doc).toContain("bun run build:default:rehearsal:check")
    expect(doc).toContain("bun run backend:candidate:rollout:check")
    expect(doc).toContain("bun run backend:candidate:verify")
    expect(doc).toContain("docs/COMPILER_DEFAULT_SWITCH_DOSSIER.md")
    expect(doc).toContain("docs/BUILD_DEFAULT_SWITCH_DOSSIER.md")
    expect(doc).toContain("docs/API_STABILITY.md")
    expect(doc).toContain("docs/EXAMPLES_POLICY.md")
    expect(doc).toContain("docs/RUNTIME_TRIAGE.md")
    expect(doc).toContain("docs/AI_WORKFLOWS.md")
    expect(doc).toContain("docs/FIRST_PRODUCTION_ROLLOUT.md")
    expect(doc).toContain("docs/ROADMAP_COMPLETION_POLICY.md")
  })

  test("package scripts expose release train checks", async () => {
    const pkg = JSON.parse(await readFile(join(REPO_ROOT, "package.json"), "utf-8")) as {
      scripts: Record<string, string>
    }
    expect(pkg.scripts["release:stable:check"]).toContain("release-channel-check.mjs stable")
    expect(pkg.scripts["release:canary:check"]).toContain("release-channel-check.mjs canary")
    expect(pkg.scripts["release:rc:check"]).toContain("release-channel-check.mjs rc")
    expect(pkg.scripts["release:version:canary"]).toContain("release-version-plan.mjs canary")
    expect(pkg.scripts["release:version:rc"]).toContain("release-version-plan.mjs rc")
    expect(pkg.scripts["release:checklist:check"]).toContain("release-checklist-check.mjs")
    expect(pkg.scripts["release:check"]).toContain("release-check.mjs")
    expect(pkg.scripts["install:matrix"]).toContain("install-matrix-check.mjs")
    expect(pkg.scripts["release:smoke"]).toContain("release-smoke.mjs")
    expect(pkg.scripts["test:provider-smoke"]).toContain("provider-smoke.test.ts")
    expect(pkg.scripts["test:browser-smoke"]).toContain("browser-smoke.mjs")
    expect(pkg.scripts["release:train:check"]).toContain("release-train-check.mjs")
    expect(pkg.scripts["compiler:promotion:check"]).toContain("compiler-promotion-check.mjs")
    expect(pkg.scripts["build:promotion:check"]).toContain("build-promotion-check.mjs")
    expect(pkg.scripts["backend:switch:evidence:check"]).toContain("backend-switch-evidence-check.mjs")
    expect(pkg.scripts["backend:default-switch:review:check"]).toContain("backend-default-switch-review-check.mjs")
    expect(pkg.scripts["backend:candidate:rollout:check"]).toContain("backend-candidate-rollout-check.mjs")
    expect(pkg.scripts["product:policy"]).toContain("product-policy-check.mjs")
    expect(pkg.scripts["ai:policy"]).toContain("ai-policy-check.mjs")
    expect(pkg.scripts["dx:policy"]).toContain("dx-policy-check.mjs")
    expect(pkg.scripts["maturity:policy"]).toContain("maturity-policy-check.mjs")
    expect(pkg.scripts["runtime:policy"]).toContain("runtime-diagnostics-policy-check.mjs")
    expect(pkg.scripts["examples:policy"]).toContain("examples-policy-check.mjs")
  })

  test("release train workflow carries widened OS and browser matrix", async () => {
    const workflow = await readFile(join(REPO_ROOT, ".github/workflows/release-train.yml"), "utf-8")
    expect(workflow).toContain("ubuntu-latest")
    expect(workflow).toContain("macos-latest")
    expect(workflow).toContain("windows-latest")
    expect(workflow).toContain("chromium")
    expect(workflow).toContain("firefox")
    expect(workflow).toContain("webkit")
    expect(workflow).toContain("PLAYWRIGHT_BROWSER: ${{ matrix.browser }}")
  })
})
