// Gorsee.js — Cloudflare Worker entry
// Auto-generated by `gorsee deploy cloudflare`

export default {
  async fetch(
    request: Request,
    env: Record<string, unknown>,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url)
    const appOrigin = (env.APP_ORIGIN as string | undefined) ?? url.origin

    // Serve static client assets from KV/site
    if (url.pathname.startsWith("/_gorsee/")) {
      const assetPath = url.pathname.slice("/_gorsee/".length)
      // @ts-expect-error — __STATIC_CONTENT is injected by Cloudflare
      const asset = await (env.__STATIC_CONTENT as any)?.get(assetPath)
      if (asset) {
        return new Response(asset, {
          headers: {
            "Content-Type": "application/javascript",
            "Cache-Control": "public, max-age=31536000, immutable",
          },
        })
      }
    }

    // Serve public static files
    const staticExts = [".css", ".ico", ".svg", ".png", ".jpg", ".woff2", ".txt"]
    if (staticExts.some((ext) => url.pathname.endsWith(ext))) {
      // @ts-expect-error — __STATIC_CONTENT is injected by Cloudflare
      const asset = await (env.__STATIC_CONTENT as any)?.get(url.pathname.slice(1))
      if (asset) {
        return new Response(asset, {
          headers: { "Cache-Control": "public, max-age=3600" },
        })
      }
    }

    // Forward all other requests to Gorsee server handler
    // In production, this imports the built server bundle
    try {
      const rpcPolicy = {
        // Wire auth/CSRF middleware here for privileged server() calls.
        // The server handler should prefer app.config.ts security.rpc.middlewares
        // when no explicit runtime policy is provided.
        middlewares: [],
      }
      const { handleRequest } = await import("./server-handler.js")
      void appOrigin
      return await handleRequest(request, env, { rpcPolicy })
    } catch {
      return new Response("Internal Server Error", { status: 500 })
    }
  },
}
