// CLI command: gorsee typegen
// Generates TypeScript route types from file-based routes

import { join } from "node:path"
import { mkdir, writeFile } from "node:fs/promises"
import { createRouter } from "../router/index.ts"
import { createProjectContext, type RuntimeOptions } from "../runtime/project.ts"
import { initializeCompilerBackends } from "../compiler/init.ts"
import {
  createRouteFactsArtifact,
  getRouteParamsRecord,
  type RouteCompilerFacts,
} from "../compiler/route-facts.ts"

const OUTPUT_DIR = ".gorsee"
const TYPES_FILE = "routes.d.ts"
const FACTS_FILE = "route-facts.json"

function formatParamsType(params: Record<string, "string">): string {
  const entries = Object.entries(params)
  if (entries.length === 0) return "{}"
  const fields = entries.map(([key, type]) => `${key}: ${type}`)
  return `{ ${fields.join("; ")} }`
}

function generateDeclaration(routes: RouteCompilerFacts[]): string {
  const lines: string[] = [
    "// Auto-generated by gorsee typegen",
    "// Do not edit manually — re-run `gorsee typegen` after adding routes",
    "",
    'declare module "gorsee/routes" {',
    "  interface RouteParams {",
  ]

  for (const route of routes) {
    const params = getRouteParamsRecord(route)
    const paramsType = formatParamsType(params)
    lines.push(`    "${route.path}": ${paramsType}`)
  }

  lines.push("  }")
  lines.push("")
  lines.push("  type RoutePath = keyof RouteParams")
  lines.push("")
  lines.push(
    "  function typedLink<P extends RoutePath>(path: P, params: RouteParams[P]): string",
  )
  lines.push(
    "  function typedNavigate<P extends RoutePath>(path: P, params: RouteParams[P]): Promise<void>",
  )
  lines.push("}")
  lines.push("")

  return lines.join("\n")
}

export interface TypegenCommandOptions extends RuntimeOptions {
  routesDir?: string
}

export async function generateRouteTypes(args: string[], options: TypegenCommandOptions = {}): Promise<void> {
  const { cwd, paths } = createProjectContext(options)
  initializeCompilerBackends(options.env ?? process.env)
  const routesDir = options.routesDir ?? args[0] ?? paths.routesDir

  console.log(`Scanning routes in: ${routesDir}`)

  const routes = await createRouter(routesDir)

  if (routes.length === 0) {
    console.warn("No routes found. Make sure your routes/ directory exists.")
    return
  }

  const outputDir = join(cwd, OUTPUT_DIR)
  await mkdir(outputDir, { recursive: true })

  const routeFacts = await createRouteFactsArtifact(routes)
  const declaration = generateDeclaration(routeFacts.routes)
  const typesPath = join(outputDir, TYPES_FILE)
  const factsPath = join(outputDir, FACTS_FILE)
  await writeFile(typesPath, declaration, "utf-8")
  await writeFile(factsPath, JSON.stringify(routeFacts, null, 2) + "\n", "utf-8")

  console.log(`Generated ${typesPath}`)
  console.log(`Generated ${factsPath}`)
  console.log(`  ${routes.length} route(s):`)
  for (const route of routes) {
    const params = route.params.length > 0 ? ` [${route.params.join(", ")}]` : ""
    console.log(`    ${route.path}${params}`)
  }
}

/** @deprecated Use generateRouteTypes() for programmatic access. */
export async function runTypegen(args: string[], options: TypegenCommandOptions = {}): Promise<void> {
  return generateRouteTypes(args, options)
}
