// Prisma integration plugin -- zero external dependencies

import type { MiddlewareFn, Context } from "../server/middleware.ts"
import type { GorseePlugin } from "./index.ts"
import { definePlugin } from "./index.ts"

export interface PrismaPluginConfig {
  schemaPath?: string
  datasourceUrl?: string
}

interface PrismaDisconnectable {
  $disconnect(): Promise<void>
}

let prismaClient: unknown = null

/** Returns the current Prisma client (available after setup) */
export function getPrisma<T = unknown>(): T {
  if (!prismaClient) {
    throw new Error("Prisma not initialized. Did you register prismaPlugin?")
  }
  return prismaClient as T
}

/** Middleware that attaches prisma to ctx.locals.prisma */
export function prismaMiddleware(client: unknown): MiddlewareFn {
  return async (ctx: Context, next) => {
    ctx.locals.prisma = client
    return next()
  }
}

/** Generates a basic schema.prisma content string */
export function generatePrismaSchema(config: PrismaPluginConfig): string {
  const url = config.datasourceUrl ?? "file:./dev.db"
  const provider = url.startsWith("file:") ? "sqlite"
    : url.startsWith("postgres") ? "postgresql"
    : "mysql"

  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "${provider}"
  url      = "${url}"
}

// Add your models below
// model User {
//   id    Int     @id @default(autoincrement())
//   email String  @unique
//   name  String?
// }
`
}

function isPrismaDisconnectable(value: unknown): value is PrismaDisconnectable {
  return typeof value === "object" && value !== null && "$disconnect" in value
    && typeof value.$disconnect === "function"
}

/** Creates a Prisma integration plugin */
export function prismaPlugin(config: PrismaPluginConfig = {}): GorseePlugin {
  return definePlugin({
    name: "gorsee-prisma",
    capabilities: ["db"],

    async setup(app) {
      try {
        // Dynamic import -- PrismaClient must be generated by user
        const { PrismaClient } = await import("@prisma/client" as string)
        prismaClient = new PrismaClient({
          datasourceUrl: config.datasourceUrl,
        })
      } catch {
        // If @prisma/client not available, create a placeholder
        prismaClient = {
          _placeholder: true,
          _message: "Run `bunx prisma generate` to create the client",
        }
      }

      app.addMiddleware(prismaMiddleware(prismaClient))
    },

    async teardown() {
      if (isPrismaDisconnectable(prismaClient)) {
        await prismaClient.$disconnect()
      }
      prismaClient = null
    },
  })
}
