// Explicit server-facing public entrypoint.
// Use this in loaders, middleware, API routes, and server services.

export * from "./server/index.ts"
/** @deprecated Prefer "gorsee/auth" when auth is the primary concern. */
export {
  createAuth,
  createMemorySessionStore,
  createNamespacedSessionStore,
  createRedisSessionStore,
  createSQLiteSessionStore,
  createAuthActionTokenManager,
  createMemoryAuthActionTokenStore,
  sessionHasRole,
  sessionHasPermission,
  type AuthConfig,
  type AuthEvent,
  type AuthEventHandler,
  type AuthActionTokenClaims,
  type AuthActionTokenPurpose,
  type AuthActionTokenReplayStore,
  type PermissionResolver,
  type Session,
  type SessionStore,
} from "./auth/index.ts"
/** @deprecated Prefer "gorsee/db" when data access is the primary concern. */
export {
  createDB,
  createPostgresDB,
  toPostgresSQL,
  type DB,
  type PostgresDB,
  type PostgresClientLike,
  type PostgresConnectionLike,
  type PostgresPoolLike,
  type PostgresQueryResult,
  runMigrations,
  createMigration,
  type MigrationResult,
} from "./db/index.ts"
/** @deprecated Prefer "gorsee/security" when security policy is the primary concern. */
export {
  securityHeaders,
  type SecurityConfig,
  csrfProtection,
  createCSRFMiddleware,
  generateCSRFToken,
  validateCSRFToken,
  createRateLimiter,
  createRedisRateLimiter,
  parseRateLimitWindow,
  type RateLimiter,
  type AsyncRateLimiter,
  type AsyncRateLimitResult,
  cors,
  type CORSOptions,
} from "./security/index.ts"
/** @deprecated Prefer "gorsee/env" when environment loading is the primary concern. */
export { env, getPublicEnv, loadEnv } from "./env/index.ts"
/** @deprecated Prefer "gorsee/log" when structured logging is the primary concern. */
export { log, setLogLevel } from "./log/index.ts"
/** @deprecated Prefer "gorsee/ai" when AI tooling is the primary concern. */
export {
  buildAIHealthReport,
  buildAIContextBundle,
  buildIDEProjection,
  configureAIObservability,
  createAIMCPServer,
  createAIContextPacket,
  createAIBridgeHandler,
  createAIBridgeServer,
  createIDEProjectionWatcher,
  createLineReader,
  emitAIDiagnostic,
  emitAIEvent,
  createTraceIds,
  readAIDiagnosticsSnapshot,
  readAIEvents,
  renderAIContextBundleMarkdown,
  renderAIContextMarkdown,
  resolveAISessionPackPaths,
  resolveIDEProjectionPaths,
  resolveAIStorePaths,
  resolveAIObservabilityConfig,
  runWithAITrace,
  writeAISessionPack,
  writeIDEProjection,
  type AIMCPServerOptions,
  type AIContextPacket,
  type AIContextBundle,
  type AIContextSnippet,
  type AIHealthReport,
  type AIEvent,
  type AIEventSeverity,
  type IDEProjection,
  type IDEProjectionPaths,
  type IDEProjectionWatcher,
  type IDEProjectionWatcherOptions,
  type AISessionPackConfig,
  type AISessionPackPaths,
  type AIStorePaths,
  type AITraceContext,
  type AIDiagnostic,
  type AIObservabilityConfig,
  type AIBridgeConfig,
  type AIBridgeServer,
  type AIBridgeHandler,
  type AIBridgeServerOptions,
  type AIBridgeSnapshot,
} from "./ai/index.ts"
export {
  createNodeRedisLikeClient,
  createIORedisLikeClient,
  deleteExpiredRedisKeys,
  type RedisLikeClient,
  type NodeRedisClientLike,
  type IORedisClientLike,
} from "./server/redis-client.ts"
export {
  createMemoryJobQueue,
  defineJob,
  type JobContext,
  type JobDefinition,
  type JobEnqueueOptions,
  type JobQueue,
  type JobRunResult,
  type EnqueuedJob,
} from "./server/jobs.ts"
/** @deprecated Prefer "gorsee/i18n" when locale contracts are the primary concern. */
export {
  setupI18n,
  loadLocale,
  getLocale,
  getLocales,
  getDefaultLocale,
  getFallbackLocales,
  setLocale,
  t,
  plural,
  negotiateLocale,
  resolveLocaleFromPath,
  stripLocalePrefix,
  withLocalePath,
  buildHreflangLinks,
  formatNumber,
  formatDate,
  formatRelativeTime,
  type I18nConfig,
  type LocaleNegotiationInput,
  type LocaleNegotiationResult,
} from "./i18n/index.ts"
/** @deprecated Prefer "gorsee/content" when content contracts are the primary concern. */
export {
  loadContentCollection,
  parseFrontmatter,
  extractExcerpt,
  queryContent,
  getContentEntryBySlug,
  type ContentCollectionOptions,
  type ContentEntry,
  type ContentQueryOptions,
} from "./content/index.ts"
