// Gorsee.js — Cloudflare Workers/Pages deploy adapter

interface CloudflareStaticContent {
  get(path: string): Promise<BodyInit | null | undefined>
}

function getStaticContent(env: Record<string, unknown>): CloudflareStaticContent | undefined {
  const value = env.__STATIC_CONTENT
  if (typeof value !== "object" || value === null || !("get" in value) || typeof value.get !== "function") {
    return undefined
  }
  return value as CloudflareStaticContent
}

export function generateWranglerConfig(name: string): string {
  const today = new Date().toISOString().split("T")[0]

  return `# Gorsee.js — Cloudflare Workers configuration
# Auto-generated by \`gorsee deploy cloudflare\`

name = "${name}"
main = "dist/worker.js"
compatibility_date = "${today}"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist/client"

[build]
command = "bun run build"

# KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = ""

# Environment variables
[vars]
NODE_ENV = "production"
APP_ORIGIN = "REPLACE_WITH_APP_ORIGIN"

# Production overrides
[env.production]
name = "${name}"
route = { pattern = "*", zone_name = "" }
`
}

export function generateCloudflareEntry(): string {
  return `// Gorsee.js — Cloudflare Worker entry
// Auto-generated by \`gorsee deploy cloudflare\`

interface CloudflareStaticContent {
  get(path: string): Promise<BodyInit | null | undefined>
}

function getStaticContent(env: Record<string, unknown>): CloudflareStaticContent | undefined {
  const value = env.__STATIC_CONTENT
  if (typeof value !== "object" || value === null || !("get" in value) || typeof value.get !== "function") {
    return undefined
  }
  return value as CloudflareStaticContent
}

export default {
  async fetch(
    request: Request,
    env: Record<string, unknown>,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url)
    const appOrigin = (env.APP_ORIGIN as string | undefined) ?? url.origin
    // __STATIC_CONTENT is injected by Cloudflare for static asset access.
    const staticContent = getStaticContent(env)

    // Serve static client assets from KV/site
    if (url.pathname.startsWith("/_gorsee/")) {
      const assetPath = url.pathname.slice("/_gorsee/".length)
      const asset = await staticContent?.get(assetPath)
      if (asset) {
        return new Response(asset, {
          headers: {
            "Content-Type": "application/javascript",
            "Cache-Control": "public, max-age=31536000, immutable",
          },
        })
      }
    }

    // Serve public static files
    const staticExts = [".css", ".ico", ".svg", ".png", ".jpg", ".woff2", ".txt"]
    if (staticExts.some((ext) => url.pathname.endsWith(ext))) {
      const asset = await staticContent?.get(url.pathname.slice(1))
      if (asset) {
        return new Response(asset, {
          headers: { "Cache-Control": "public, max-age=3600" },
        })
      }
    }

    // Forward all other requests to Gorsee server handler
    // In production, this imports the built server bundle
    try {
      const rpcPolicy = {
        // Wire auth/CSRF middleware here for privileged server() calls.
        // The server handler should prefer app.config.ts security.rpc.middlewares
        // when no explicit runtime policy is provided.
        middlewares: [],
      }
      const { handleRequest } = await import("./dist/server-handler.js")
      void appOrigin
      return await handleRequest(request, env, { rpcPolicy })
    } catch {
      return new Response("Internal Server Error", { status: 500 })
    }
  },
}
`
}

export interface CloudflareRoutesConfig {
  version: number
  include: string[]
  exclude: string[]
}

export function generateCloudflareStaticAssets(): CloudflareRoutesConfig {
  return {
    version: 1,
    include: ["/*"],
    exclude: [
      "/_gorsee/*",
      "/favicon.ico",
      "/robots.txt",
      "/styles.css",
      "/*.png",
      "/*.jpg",
      "/*.svg",
      "/*.woff2",
    ],
  }
}
