// Gorsee.js — Fly.io deploy adapter

import type { ProcessDeployRuntime } from "./runtime.ts"

export function generateFlyConfig(appName: string): string {
  return `# Gorsee.js — Fly.io configuration
# Auto-generated by \`gorsee deploy fly\`

app = "${appName}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  APP_ORIGIN = "REPLACE_WITH_APP_ORIGIN"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/api/health"
  timeout = "5s"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  processes = ["app"]
  count_min = 1
  count_max = 3
`
}

export function generateFlyDockerfile(runtime: ProcessDeployRuntime = "bun"): string {
  const runtimeImage = runtime === "node" ? "node:20-bookworm-slim" : "oven/bun:1-slim"
  const runtimeCommand = runtime === "node"
    ? 'CMD ["node", "dist/prod-node.js"]'
    : 'CMD ["bun", "run", "start"]'

  return `# Gorsee.js — Fly.io optimized Dockerfile
# Auto-generated by \`gorsee deploy fly\`
# Runtime profile: ${runtime}

FROM oven/bun:1 AS builder
WORKDIR /app
COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM ${runtimeImage}
WORKDIR /app

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/public ./public
COPY --from=builder /app/.env* ./

ENV NODE_ENV=production
ENV PORT=3000
ENV APP_ORIGIN=REPLACE_WITH_APP_ORIGIN

# Fly.io runtime env vars are injected automatically:
# FLY_ALLOC_ID, FLY_APP_NAME, FLY_REGION, FLY_MACHINE_ID

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \\
  CMD curl -f http://localhost:3000/api/health || exit 1

${runtimeCommand}
`
}
