// Gorsee.js — Netlify deploy adapter

export function generateNetlifyConfig(): string {
  return `# Gorsee.js — Netlify configuration
# Auto-generated by \`gorsee deploy netlify\`

[build]
  command = "bun run build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "20"
  APP_ORIGIN = "REPLACE_WITH_APP_ORIGIN"

[[edge_functions]]
  function = "gorsee-handler"
  path = "/*"

# Static assets bypass edge functions
[[edge_functions]]
  function = "gorsee-handler"
  path = "/_gorsee/*"
  excludedPath = true

[[redirects]]
  from = "/_gorsee/*"
  to = "/client/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/gorsee-handler"
  status = 200
  force = false

[[headers]]
  for = "/_gorsee/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
`
}

export function generateNetlifyFunction(): string {
  return `// Gorsee.js — Netlify Edge Function
// Auto-generated by \`gorsee deploy netlify\`
// Place in: netlify/edge-functions/gorsee-handler.ts

import type { Context } from "https://edge.netlify.com"

export default async function handler(
  request: Request,
  context: Context,
): Promise<Response> {
  const url = new URL(request.url)
  const appOrigin = Netlify.env.get("APP_ORIGIN") ?? url.origin

  // Skip static assets — handled by Netlify CDN
  if (url.pathname.startsWith("/_gorsee/")) {
    return context.next()
  }

  const staticExts = [".css", ".ico", ".svg", ".png", ".jpg", ".woff2", ".txt"]
  if (staticExts.some((ext) => url.pathname.endsWith(ext))) {
    return context.next()
  }

  // Forward to Gorsee server handler
  try {
    const rpcPolicy = {
      // Wire auth/CSRF middleware here for privileged server() calls.
      // The server handler should prefer app.config.ts security.rpc.middlewares
      // when no explicit runtime policy is provided.
      middlewares: [],
    }
    const { handleRequest } = await import("../../dist/server-handler.js")
    void appOrigin
    return await handleRequest(request, { netlifyContext: context }, { rpcPolicy })
  } catch (err) {
    console.error("Gorsee handler error:", err)
    return new Response("Internal Server Error", { status: 500 })
  }
}

export const config = { path: "/*" }
`
}
