// Gorsee.js — Vercel deploy adapter

export interface VercelConfig {
  version: number
  framework: null
  buildCommand: string
  outputDirectory: string
  routes: Array<{ src: string; dest?: string; headers?: Record<string, string> }>
}

export function generateVercelConfig(): VercelConfig {
  return {
    version: 2,
    framework: null,
    buildCommand: "bun run build",
    outputDirectory: ".vercel/output",
    routes: [
      {
        src: "/_gorsee/(.*)",
        headers: { "Cache-Control": "public, max-age=31536000, immutable" },
      },
      { src: "/(.*)", dest: "/api/index" },
    ],
  }
}

export function generateVercelServerlessEntry(): string {
  return `// Gorsee.js — Vercel serverless entry
// Auto-generated by \`gorsee deploy vercel\`

import { handleRequest } from "../dist/server-handler-node.js"

export default async function handler(request: Request): Promise<Response> {
  const url = new URL(request.url)
  // Set APP_ORIGIN in your Vercel project environment before production traffic.
  const appOrigin = process.env.APP_ORIGIN ?? url.origin
  void appOrigin

  const rpcPolicy = {
    // Wire auth/CSRF middleware here for privileged server() calls.
    middlewares: [],
  }

  return handleRequest(request, { vercel: true }, { rpcPolicy })
}
`
}

export interface VercelOutputConfig {
  version: number
  routes: Array<{ src: string; dest?: string; headers?: Record<string, string> }>
}

export function generateVercelBuildOutput(routes: string[]): VercelOutputConfig {
  const outputRoutes: VercelOutputConfig["routes"] = [
    {
      src: "/_gorsee/(.*)",
      dest: "/static/_gorsee/$1",
      headers: { "Cache-Control": "public, max-age=31536000, immutable" },
    },
    {
      src: "/favicon\\.ico|/robots\\.txt|/styles\\.css",
      dest: "/static/$0",
    },
  ]

  for (const route of routes) {
    outputRoutes.push({ src: route, dest: "/functions/index" })
  }

  outputRoutes.push({ src: "/(.*)", dest: "/functions/index" })

  return { version: 3, routes: outputRoutes }
}
